### PR TITLE
Move files from my-app to root directory

### PR DESCRIPTION
**Pull request by Logan-Dang**
Having a single folder in the root directory is redundant. Moved all files out as standard.

### CODE REVIEW

**Comment by 5465869** [comment]
Hi @Logan-Dang  do I know you?

**Comment by Logan-Dang** [comment]
@5465869 Found this project through goodfirstissues.com. I have an interest in chess so I wanted to help out. If you don't want me to work with you, it's okay

**Comment by 5465869** [comment]
@Logan-Dang  haha didn't know such a thing existed. I'd recommend contributing to a real repo for your first issue, but you are welcome to make pull requests on this repo with the caveat that I will be pretty opinionated what gets merged in. You do have a valid point about the redundant root folder. Think I initialized the repo and then ran create-react-app inside of it. However, this will create a merge conflict for the other pr out there so I think I'm going to close it. You're welcome to do the same thing again after that one gets merged. I'd prefer anything that is contributed is either an issue in the issue tracker or if you have a suggestion for something you want to do that isn't in the issue tracker that you create an issue for it to be discussed there first.

**Comment by Logan-Dang** [comment]
Sounds good

**Pull request closed without merging**
